### ISSUE TITLE
Is it possible to publish the extension on the marketplace?

### ISSUE THREAD

**Issue by DonPavlov** [tiffon/vscode-todone#1]
Would love to see the extension on the marketplace.
Also it would not feel right to do it myself. 
https://code.visualstudio.com/docs/extensions/publish-extension

I mean i could do it and would reference you as code author. but still.

**Comment by dcrystalj** [comment]
@dehein please do it

**Comment by dcrystalj** [comment]
@DonPavlov will you do it?

**Comment by DonPavlov** [comment]
Sorry stopped using todone a long time ago and the answer came quite late. Will take a look into it again on the weekends, what needs to be done. Will probably fork it and publish my own, makes it easier license wise for the marketplace.
